/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class BoxClipRectangle {

    public BoxClipRectangle(float x, float y, float width, float height) {
        this.x = float;
        this.y = float;
        this.width = float;
        this.height = float;
        this.type = "box";
    }

    private final box type;
    public getType(box type) {
        this.type = type;
    }

    private final float x;
    public getX(float x) {
        this.x = x;
    }

    private final float y;
    public getY(float y) {
        this.y = y;
    }

    private final float width;
    public getWidth(float width) {
        this.width = width;
    }

    private final float height;
    public getHeight(float height) {
        this.height = height;
    }

}