/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class CaptureScreenshotResult {

    public CaptureScreenshotResult(String data) {
        this.data = String;
        
    }

    private final String data;
    public getData(String data) {
        this.data = data;
    }

}