/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class CloseParameters {

    public CloseParameters(BrowsingContext.BrowsingContext context, Unknown promptUnload) {
        this.context = BrowsingContext.BrowsingContext;
        this.promptUnload = Unknown;
        
    }

    private final BrowsingContext.BrowsingContext context;
    public getContext(BrowsingContext.BrowsingContext context) {
        this.context = context;
    }

    private final Unknown promptUnload;
    public getPromptUnload(Unknown promptUnload) {
        this.promptUnload = promptUnload;
    }

}