/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class ContextLocator {

    public ContextLocator(Unknown value) {
        this.value = Unknown;
        this.type = "context";
    }

    private final context type;
    public getType(context type) {
        this.type = type;
    }

    private final Unknown value;
    public getValue(Unknown value) {
        this.value = value;
    }

}