/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class DownloadWillBeginParams {

    public DownloadWillBeginParams(String suggestedFilename) {
        this.suggestedFilename = String;
        
    }

    private final String suggestedFilename;
    public getSuggestedFilename(String suggestedFilename) {
        this.suggestedFilename = suggestedFilename;
    }

}