/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class GetTreeParameters {

    public GetTreeParameters(long maxDepth, BrowsingContext.BrowsingContext root) {
        this.maxDepth = long;
        this.root = BrowsingContext.BrowsingContext;
        
    }

    private final long maxDepth;
    public getMaxDepth(long maxDepth) {
        this.maxDepth = maxDepth;
    }

    private final BrowsingContext.BrowsingContext root;
    public getRoot(BrowsingContext.BrowsingContext root) {
        this.root = root;
    }

}