/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class GetTreeResult {

    public GetTreeResult(BrowsingContext.InfoList contexts) {
        this.contexts = BrowsingContext.InfoList;
        
    }

    private final BrowsingContext.InfoList contexts;
    public getContexts(BrowsingContext.InfoList contexts) {
        this.contexts = contexts;
    }

}