/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class HistoryUpdatedParameters {

    public HistoryUpdatedParameters(BrowsingContext.BrowsingContext context, String url) {
        this.context = BrowsingContext.BrowsingContext;
        this.url = String;
        
    }

    private final BrowsingContext.BrowsingContext context;
    public getContext(BrowsingContext.BrowsingContext context) {
        this.context = context;
    }

    private final String url;
    public getUrl(String url) {
        this.url = url;
    }

}