/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class ImageFormat {

    public ImageFormat(String type, Unknown quality) {
        this.type = String;
        this.quality = Unknown;
        
    }

    private final String type;
    public getType(String type) {
        this.type = type;
    }

    private final Unknown quality;
    public getQuality(Unknown quality) {
        this.quality = quality;
    }

}