/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class LocateNodesResult {

    public LocateNodesResult() {
        
        this.nodes = "Unknown[]";
    }

    private final Unknown[] nodes;
    public getNodes(Unknown[] nodes) {
        this.nodes = nodes;
    }

}