/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.browsingcontext;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for browsingContext.LocateNodesResult command
 */
public class LocateNodesResult {

    /**
     * Creates a new LocateNodesResult instance
     */
    public LocateNodesResult(List<Object> nodes) {
        this.nodes = nodes;
        
    }

    private final List<Object> nodes;

    /**
     * Gets the nodes property
     * @return List<Object> value
     */
    public List<Object> getNodes() {
        return this.nodes;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("nodes", this.nodes);
        return toReturn;
    }

}