/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class NavigateResult {

    public NavigateResult(Unknown navigation, String url) {
        this.navigation = Unknown;
        this.url = String;
        
    }

    private final Unknown navigation;
    public getNavigation(Unknown navigation) {
        this.navigation = navigation;
    }

    private final String url;
    public getUrl(String url) {
        this.url = url;
    }

}