/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class PrintPageParameters {

    public PrintPageParameters(float height, float width) {
        this.height = float;
        this.width = float;
        
    }

    private final float height;
    public getHeight(float height) {
        this.height = height;
    }

    private final float width;
    public getWidth(float width) {
        this.width = width;
    }

}