/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.BrowsingContext;


public class Viewport {

    public Viewport(long width, long height) {
        this.width = long;
        this.height = long;
        
    }

    private final long width;
    public getWidth(long width) {
        this.width = width;
    }

    private final long height;
    public getHeight(long height) {
        this.height = height;
    }

}