/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.script;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for script.AddPreloadScriptParameters command
 */
public class AddPreloadScriptParameters {

    /**
     * Creates a new AddPreloadScriptParameters instance
     */
    public AddPreloadScriptParameters(String functionDeclaration, List<Object> arguments, List<Object> contexts, List<Object> userContexts, String sandbox) {
        this.functionDeclaration = functionDeclaration;
        this.arguments = arguments;
        this.contexts = contexts;
        this.userContexts = userContexts;
        this.sandbox = sandbox;
        
    }

    private final String functionDeclaration;

    /**
     * Gets the functionDeclaration property
     * @return String value
     */
    public String getFunctionDeclaration() {
        return this.functionDeclaration;
    }

    private final List<Object> arguments;

    /**
     * Gets the arguments property
     * @return List<Object> value
     */
    public List<Object> getArguments() {
        return this.arguments;
    }

    private final List<Object> contexts;

    /**
     * Gets the contexts property
     * @return List<Object> value
     */
    public List<Object> getContexts() {
        return this.contexts;
    }

    private final List<Object> userContexts;

    /**
     * Gets the userContexts property
     * @return List<Object> value
     */
    public List<Object> getUserContexts() {
        return this.userContexts;
    }

    private final String sandbox;

    /**
     * Gets the sandbox property
     * @return String value
     */
    public String getSandbox() {
        return this.sandbox;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("functionDeclaration", this.functionDeclaration);
        toReturn.put("arguments", this.arguments);
        toReturn.put("contexts", this.contexts);
        toReturn.put("userContexts", this.userContexts);
        toReturn.put("sandbox", this.sandbox);
        return toReturn;
    }

}