/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class AddPreloadScriptResult {

    public AddPreloadScriptResult(Script.PreloadScript script) {
        this.script = Script.PreloadScript;
        
    }

    private final Script.PreloadScript script;
    public getScript(Script.PreloadScript script) {
        this.script = script;
    }

}