/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class BaseRealmInfo {

    public BaseRealmInfo(Script.Realm realm, String origin) {
        this.realm = Script.Realm;
        this.origin = String;
        
    }

    private final Script.Realm realm;
    public getRealm(Script.Realm realm) {
        this.realm = realm;
    }

    private final String origin;
    public getOrigin(String origin) {
        this.origin = origin;
    }

}