/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class BooleanValue {

    public BooleanValue(boolean value) {
        this.value = boolean;
        this.type = "boolean";
    }

    private final boolean type;
    public getType(boolean type) {
        this.type = type;
    }

    private final boolean value;
    public getValue(boolean value) {
        this.value = value;
    }

}