/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class ChannelValue {

    public ChannelValue(Script.ChannelProperties value) {
        this.value = Script.ChannelProperties;
        this.type = "channel";
    }

    private final channel type;
    public getType(channel type) {
        this.type = type;
    }

    private final Script.ChannelProperties value;
    public getValue(Script.ChannelProperties value) {
        this.value = value;
    }

}