/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class ContextTarget {

    public ContextTarget(BrowsingContext.BrowsingContext context, String sandbox) {
        this.context = BrowsingContext.BrowsingContext;
        this.sandbox = String;
        
    }

    private final BrowsingContext.BrowsingContext context;
    public getContext(BrowsingContext.BrowsingContext context) {
        this.context = context;
    }

    private final String sandbox;
    public getSandbox(String sandbox) {
        this.sandbox = sandbox;
    }

}