/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class DateLocalValue {

    public DateLocalValue(String value) {
        this.value = String;
        this.type = "date";
    }

    private final date type;
    public getType(date type) {
        this.type = type;
    }

    private final String value;
    public getValue(String value) {
        this.value = value;
    }

}