/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class DedicatedWorkerRealmInfo {

    public DedicatedWorkerRealmInfo() {
        
        this.type = "dedicated-worker";
        this.owners = "Unknown[]";
    }

    private final dedicated-worker type;
    public getType(dedicated-worker type) {
        this.type = type;
    }

    private final Unknown[] owners;
    public getOwners(Unknown[] owners) {
        this.owners = owners;
    }

}