/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class DisownParameters {

    public DisownParameters(Script.Target target) {
        this.target = Script.Target;
        this.handles = "Unknown[]";
    }

    private final Unknown[] handles;
    public getHandles(Unknown[] handles) {
        this.handles = handles;
    }

    private final Script.Target target;
    public getTarget(Script.Target target) {
        this.target = target;
    }

}