/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class EvaluateResultSuccess {

    public EvaluateResultSuccess(Script.RemoteValue result, Script.Realm realm) {
        this.result = Script.RemoteValue;
        this.realm = Script.Realm;
        this.type = "success";
    }

    private final success type;
    public getType(success type) {
        this.type = type;
    }

    private final Script.RemoteValue result;
    public getResult(Script.RemoteValue result) {
        this.result = result;
    }

    private final Script.Realm realm;
    public getRealm(Script.Realm realm) {
        this.realm = realm;
    }

}