/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class EvaluateResultException {

    public EvaluateResultException(Script.ExceptionDetails exceptionDetails, Script.Realm realm) {
        this.exceptionDetails = Script.ExceptionDetails;
        this.realm = Script.Realm;
        this.type = "exception";
    }

    private final exception type;
    public getType(exception type) {
        this.type = type;
    }

    private final Script.ExceptionDetails exceptionDetails;
    public getExceptionDetails(Script.ExceptionDetails exceptionDetails) {
        this.exceptionDetails = exceptionDetails;
    }

    private final Script.Realm realm;
    public getRealm(Script.Realm realm) {
        this.realm = realm;
    }

}