/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class NullValue {

    public NullValue(Unknown type) {
        this.type = Unknown;
        
    }

    private final Unknown type;
    public getType(Unknown type) {
        this.type = type;
    }

}