/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class NumberValue {

    public NumberValue(Unknown value) {
        this.value = Unknown;
        this.type = "number";
    }

    private final number type;
    public getType(number type) {
        this.type = type;
    }

    private final Unknown value;
    public getValue(Unknown value) {
        this.value = value;
    }

}