/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class ObjectLocalValue {

    public ObjectLocalValue(Script.MappingLocalValue value) {
        this.value = Script.MappingLocalValue;
        this.type = "object";
    }

    private final object type;
    public getType(object type) {
        this.type = type;
    }

    private final Script.MappingLocalValue value;
    public getValue(Script.MappingLocalValue value) {
        this.value = value;
    }

}