/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class RegExpLocalValue {

    public RegExpLocalValue(Script.RegExpValue value) {
        this.value = Script.RegExpValue;
        this.type = "regexp";
    }

    private final regexp type;
    public getType(regexp type) {
        this.type = type;
    }

    private final Script.RegExpValue value;
    public getValue(Script.RegExpValue value) {
        this.value = value;
    }

}