/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class RemoteObjectReference {

    public RemoteObjectReference(Script.Handle handle, Script.SharedId sharedId) {
        this.handle = Script.Handle;
        this.sharedId = Script.SharedId;
        
    }

    private final Script.Handle handle;
    public getHandle(Script.Handle handle) {
        this.handle = handle;
    }

    private final Script.SharedId sharedId;
    public getSharedId(Script.SharedId sharedId) {
        this.sharedId = sharedId;
    }

}