/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class ServiceWorkerRealmInfo {

    public ServiceWorkerRealmInfo() {
        
        this.type = "service-worker";
    }

    private final service-worker type;
    public getType(service-worker type) {
        this.type = type;
    }

}