/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class SharedWorkerRealmInfo {

    public SharedWorkerRealmInfo() {
        
        this.type = "shared-worker";
    }

    private final shared-worker type;
    public getType(shared-worker type) {
        this.type = type;
    }

}