/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.script;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for script.SharedReference command
 */
public class SharedReference {

    /**
     * Creates a new SharedReference instance
     */
    public SharedReference(Script.SharedId sharedId, Script.Handle handle) {
        this.sharedId = sharedId;
        this.handle = handle;
        
    }

    private final Script.SharedId sharedId;

    /**
     * Gets the sharedId property
     * @return Script.SharedId value
     */
    public Script.SharedId getSharedId() {
        return this.sharedId;
    }

    private final Script.Handle handle;

    /**
     * Gets the handle property
     * @return Script.Handle value
     */
    public Script.Handle getHandle() {
        return this.handle;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("sharedId", this.sharedId);
        toReturn.put("handle", this.handle);
        return toReturn;
    }

}