/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Script;


public class StackTrace {

    public StackTrace() {
        
        this.callFrames = "Unknown[]";
    }

    private final Unknown[] callFrames;
    public getCallFrames(Unknown[] callFrames) {
        this.callFrames = callFrames;
    }

}