/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.browser;

import org.openqa.selenium.bidi.Command;

/**
 * Auto generated class for running Bidi commands in Java
 */
public class BrowserModule {

    /**
     * WebDriver Bidi command to send command method "browser.setClientWindowState" with parameters.
     * @url https://w3c.github.io/webdriver-bidi/#command-browser-setClientWindowState
     * @param params `BrowserSetClientWindowStateParameters` {@link https://w3c.github.io/webdriver-bidi/#command-browser-setClientWindowState | command parameter}
     */
    public Command<EmptyResult> SetClientWindowState (SetClientWindowStateParameters parameters) {
        return new Command<>(
            "browser.setClientWindowState",
            parameters.asMap(),
            EmptyResult.class
        );
    }
}