/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Browser;


public class ClientWindowNamedState {

    public ClientWindowNamedState(Unknown state) {
        this.state = Unknown;
        
    }

    private final Unknown state;
    public getState(Unknown state) {
        this.state = state;
    }

}