/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.browser;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.EmptyResult;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents response for browser.CreateUserContextResult command
 */
public class CreateUserContextResult {

    /**
     * Creates a new CreateUserContextResult instance
     */
    public CreateUserContextResult() {
        // No properties to initialize
    }
