/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Browser;


public class SetClientWindowStateParameters {

    public SetClientWindowStateParameters(Browser.ClientWindow clientWindow) {
        this.clientWindow = Browser.ClientWindow;
        
    }

    private final Browser.ClientWindow clientWindow;
    public getClientWindow(Browser.ClientWindow clientWindow) {
        this.clientWindow = clientWindow;
    }

}