/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.WebExtension;


public class ExtensionBase64Encoded {

    public ExtensionBase64Encoded(String value) {
        this.value = String;
        this.type = "base64";
    }

    private final base64 type;
    public getType(base64 type) {
        this.type = type;
    }

    private final String value;
    public getValue(String value) {
        this.value = value;
    }

}