/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.WebExtension;


public class ExtensionArchivePath {

    public ExtensionArchivePath(String path) {
        this.path = String;
        this.type = "archivePath";
    }

    private final archivePath type;
    public getType(archivePath type) {
        this.type = type;
    }

    private final String path;
    public getPath(String path) {
        this.path = path;
    }

}