/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.WebExtension;


public class InstallParameters {

    public InstallParameters(WebExtension.ExtensionData extensionData) {
        this.extensionData = WebExtension.ExtensionData;
        
    }

    private final WebExtension.ExtensionData extensionData;
    public getExtensionData(WebExtension.ExtensionData extensionData) {
        this.extensionData = extensionData;
    }

}