/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.WebExtension;


public class UninstallParameters {

    public UninstallParameters(WebExtension.Extension extension) {
        this.extension = WebExtension.Extension;
        
    }

    private final WebExtension.Extension extension;
    public getExtension(WebExtension.Extension extension) {
        this.extension = extension;
    }

}