/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Storage;


public class BrowsingContextPartitionDescriptor {

    public BrowsingContextPartitionDescriptor(BrowsingContext.BrowsingContext context) {
        this.context = BrowsingContext.BrowsingContext;
        this.type = "context";
    }

    private final context type;
    public getType(context type) {
        this.type = type;
    }

    private final BrowsingContext.BrowsingContext context;
    public getContext(BrowsingContext.BrowsingContext context) {
        this.context = context;
    }

}