/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Storage;


public class GetCookiesResult {

    public GetCookiesResult(Storage.PartitionKey partitionKey) {
        this.partitionKey = Storage.PartitionKey;
        this.cookies = "Unknown[]";
    }

    private final Unknown[] cookies;
    public getCookies(Unknown[] cookies) {
        this.cookies = cookies;
    }

    private final Storage.PartitionKey partitionKey;
    public getPartitionKey(Storage.PartitionKey partitionKey) {
        this.partitionKey = partitionKey;
    }

}