/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Storage;


public class PartitionKey {

    public PartitionKey(String userContext, String sourceOrigin) {
        this.userContext = String;
        this.sourceOrigin = String;
        
    }

    private final String userContext;
    public getUserContext(String userContext) {
        this.userContext = userContext;
    }

    private final String sourceOrigin;
    public getSourceOrigin(String sourceOrigin) {
        this.sourceOrigin = sourceOrigin;
    }

}