/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Storage;


public class SetCookieParameters {

    public SetCookieParameters(Storage.PartialCookie cookie, Storage.PartitionDescriptor partition) {
        this.cookie = Storage.PartialCookie;
        this.partition = Storage.PartitionDescriptor;
        
    }

    private final Storage.PartialCookie cookie;
    public getCookie(Storage.PartialCookie cookie) {
        this.cookie = cookie;
    }

    private final Storage.PartitionDescriptor partition;
    public getPartition(Storage.PartitionDescriptor partition) {
        this.partition = partition;
    }

}