/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Emulation;


public class SetGeolocationOverrideParameters {

    public SetGeolocationOverrideParameters(Unknown coordinates) {
        this.coordinates = Unknown;
        this.contexts = "Unknown[]";
        this.userContexts = "Unknown[]";
    }

    private final Unknown coordinates;
    public getCoordinates(Unknown coordinates) {
        this.coordinates = coordinates;
    }

    private final Unknown[] contexts;
    public getContexts(Unknown[] contexts) {
        this.contexts = contexts;
    }

    private final Unknown[] userContexts;
    public getUserContexts(Unknown[] userContexts) {
        this.userContexts = userContexts;
    }

}