/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.emulation;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for emulation.SetGeolocationOverrideParameters command
 */
public class SetGeolocationOverrideParameters {

    /**
     * Creates a new SetGeolocationOverrideParameters instance
     */
    public SetGeolocationOverrideParameters(Object coordinates, List<Object> contexts, List<Object> userContexts) {
        this.coordinates = coordinates;
        this.contexts = contexts;
        this.userContexts = userContexts;
        
    }

    private final Object coordinates;

    /**
     * Gets the coordinates property
     * @return Object value
     */
    public Object getCoordinates() {
        return this.coordinates;
    }

    private final List<Object> contexts;

    /**
     * Gets the contexts property
     * @return List<Object> value
     */
    public List<Object> getContexts() {
        return this.contexts;
    }

    private final List<Object> userContexts;

    /**
     * Gets the userContexts property
     * @return List<Object> value
     */
    public List<Object> getUserContexts() {
        return this.userContexts;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("coordinates", this.coordinates);
        toReturn.put("contexts", this.contexts);
        toReturn.put("userContexts", this.userContexts);
        return toReturn;
    }

}