/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Session;


public class NewParameters {

    public NewParameters(Session.CapabilitiesRequest capabilities) {
        this.capabilities = Session.CapabilitiesRequest;
        
    }

    private final Session.CapabilitiesRequest capabilities;
    public getCapabilities(Session.CapabilitiesRequest capabilities) {
        this.capabilities = capabilities;
    }

}