/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Session;


public class NewResult {

    public NewResult(String sessionId, Unknown capabilities) {
        this.sessionId = String;
        this.capabilities = Unknown;
        
    }

    private final String sessionId;
    public getSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    private final Unknown capabilities;
    public getCapabilities(Unknown capabilities) {
        this.capabilities = capabilities;
    }

}