/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Session;


public class StatusResult {

    public StatusResult(boolean ready, String message) {
        this.ready = boolean;
        this.message = String;
        
    }

    private final boolean ready;
    public getReady(boolean ready) {
        this.ready = ready;
    }

    private final String message;
    public getMessage(String message) {
        this.message = message;
    }

}