/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Session;


public class SubscribeResult {

    public SubscribeResult(Session.Subscription subscription) {
        this.subscription = Session.Subscription;
        
    }

    private final Session.Subscription subscription;
    public getSubscription(Session.Subscription subscription) {
        this.subscription = subscription;
    }

}