/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Session;


public class UnsubscribeByAttributesRequest {

    public UnsubscribeByAttributesRequest() {
        
        this.events = "Unknown[]";
        this.contexts = "Unknown[]";
    }

    private final Unknown[] events;
    public getEvents(Unknown[] events) {
        this.events = events;
    }

    private final Unknown[] contexts;
    public getContexts(Unknown[] contexts) {
        this.contexts = contexts;
    }

}