/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class AddInterceptParameters {

    public AddInterceptParameters() {
        
        this.phases = "Unknown[]";
        this.contexts = "Unknown[]";
        this.urlPatterns = "Unknown[]";
    }

    private final Unknown[] phases;
    public getPhases(Unknown[] phases) {
        this.phases = phases;
    }

    private final Unknown[] contexts;
    public getContexts(Unknown[] contexts) {
        this.contexts = contexts;
    }

    private final Unknown[] urlPatterns;
    public getUrlPatterns(Unknown[] urlPatterns) {
        this.urlPatterns = urlPatterns;
    }

}