/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class AuthChallenge {

    public AuthChallenge(String scheme, String realm) {
        this.scheme = String;
        this.realm = String;
        
    }

    private final String scheme;
    public getScheme(String scheme) {
        this.scheme = scheme;
    }

    private final String realm;
    public getRealm(String realm) {
        this.realm = realm;
    }

}