/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class AuthCredentials {

    public AuthCredentials(String username, String password) {
        this.username = String;
        this.password = String;
        this.type = "password";
    }

    private final password type;
    public getType(password type) {
        this.type = type;
    }

    private final String username;
    public getUsername(String username) {
        this.username = username;
    }

    private final String password;
    public getPassword(String password) {
        this.password = password;
    }

}