/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class BeforeRequestSentParameters {

    public BeforeRequestSentParameters(Network.Initiator initiator) {
        this.initiator = Network.Initiator;
        
    }

    private final Network.Initiator initiator;
    public getInitiator(Network.Initiator initiator) {
        this.initiator = initiator;
    }

}