/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class ContinueWithAuthNoCredentials {

    public ContinueWithAuthNoCredentials(Unknown action) {
        this.action = Unknown;
        
    }

    private final Unknown action;
    public getAction(Unknown action) {
        this.action = action;
    }

}