/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class ContinueWithAuthParameters {

    public ContinueWithAuthParameters(Network.Request request) {
        this.request = Network.Request;
        
    }

    private final Network.Request request;
    public getRequest(Network.Request request) {
        this.request = request;
    }

}