/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class ContinueWithAuthCredentials {

    public ContinueWithAuthCredentials(Network.AuthCredentials credentials) {
        this.credentials = Network.AuthCredentials;
        this.action = "provideCredentials";
    }

    private final provideCredentials action;
    public getAction(provideCredentials action) {
        this.action = action;
    }

    private final Network.AuthCredentials credentials;
    public getCredentials(Network.AuthCredentials credentials) {
        this.credentials = credentials;
    }

}