/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class FetchErrorParameters {

    public FetchErrorParameters(String errorText) {
        this.errorText = String;
        
    }

    private final String errorText;
    public getErrorText(String errorText) {
        this.errorText = errorText;
    }

}