/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class Header {

    public Header(String name, Network.BytesValue value) {
        this.name = String;
        this.value = Network.BytesValue;
        
    }

    private final String name;
    public getName(String name) {
        this.name = name;
    }

    private final Network.BytesValue value;
    public getValue(Network.BytesValue value) {
        this.value = value;
    }

}