/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.network;

import org.openqa.selenium.bidi.Command;

/**
 * Auto generated class for running Bidi commands in Java
 */
public class NetworkModule {

    /**
     * WebDriver Bidi command to send command method "network.setCacheBehavior" with parameters.
     * @url https://w3c.github.io/webdriver-bidi/#command-network-setCacheBehavior
     * @param params `NetworkSetCacheBehaviorParameters` {@link https://w3c.github.io/webdriver-bidi/#command-network-setCacheBehavior | command parameter}
     */
    public Command<EmptyResult> SetCacheBehavior (SetCacheBehaviorParameters parameters) {
        return new Command<>(
            "network.setCacheBehavior",
            parameters.asMap(),
            EmptyResult.class
        );
    }
}