/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class RemoveInterceptParameters {

    public RemoveInterceptParameters(Network.Intercept intercept) {
        this.intercept = Network.Intercept;
        
    }

    private final Network.Intercept intercept;
    public getIntercept(Network.Intercept intercept) {
        this.intercept = intercept;
    }

}