/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class ResponseStartedParameters {

    public ResponseStartedParameters(Network.ResponseData response) {
        this.response = Network.ResponseData;
        
    }

    private final Network.ResponseData response;
    public getResponse(Network.ResponseData response) {
        this.response = response;
    }

}