/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class ResponseContent {

    public ResponseContent(long size) {
        this.size = long;
        
    }

    private final long size;
    public getSize(long size) {
        this.size = size;
    }

}