/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class SetCacheBehaviorParameters {

    public SetCacheBehaviorParameters(Unknown cacheBehavior) {
        this.cacheBehavior = Unknown;
        this.contexts = "Unknown[]";
    }

    private final Unknown cacheBehavior;
    public getCacheBehavior(Unknown cacheBehavior) {
        this.cacheBehavior = cacheBehavior;
    }

    private final Unknown[] contexts;
    public getContexts(Unknown[] contexts) {
        this.contexts = contexts;
    }

}