/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Network;


public class UrlPatternString {

    public UrlPatternString(String pattern) {
        this.pattern = String;
        this.type = "string";
    }

    private final string type;
    public getType(string type) {
        this.type = type;
    }

    private final String pattern;
    public getPattern(String pattern) {
        this.pattern = pattern;
    }

}