/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.input;

import org.openqa.selenium.bidi.Command;

/**
 * Auto generated class for running Bidi commands in Java
 */
public class InputModule {

    /**
     * WebDriver Bidi command to send command method "input.fileDialogOpened" with parameters.
     * @url https://w3c.github.io/webdriver-bidi/#command-input-fileDialogOpened
     * @param params `InputFileDialogInfo` {@link https://w3c.github.io/webdriver-bidi/#command-input-fileDialogOpened | command parameter}
     */
    public Command<EmptyResult> FileDialogOpened (FileDialogInfo parameters) {
        return new Command<>(
            "input.fileDialogOpened",
            parameters.asMap(),
            EmptyResult.class
        );
    }
}