/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Input;


public class KeyUpAction {

    public KeyUpAction(String value) {
        this.value = String;
        this.type = "keyUp";
    }

    private final keyUp type;
    public getType(keyUp type) {
        this.type = type;
    }

    private final String value;
    public getValue(String value) {
        this.value = value;
    }

}