/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Input;


public class NoneSourceActions {

    public NoneSourceActions(String id) {
        this.id = String;
        this.type = "none";
        this.actions = "Unknown[]";
    }

    private final none type;
    public getType(none type) {
        this.type = type;
    }

    private final String id;
    public getId(String id) {
        this.id = id;
    }

    private final Unknown[] actions;
    public getActions(Unknown[] actions) {
        this.actions = actions;
    }

}