/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.input;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for input.NoneSourceActions command
 */
public class NoneSourceActions {

    /**
     * Creates a new NoneSourceActions instance
     */
    public NoneSourceActions(String id, List<Unknown> actions) {
        this.id = id;
        this.actions = actions;
        this.type = "none";
    }

    private final none type;

    /**
     * Gets the type property
     * @return none value
     */
    public none getType() {
        return this.type;
    }

    private final String id;

    /**
     * Gets the id property
     * @return String value
     */
    public String getId() {
        return this.id;
    }

    private final List<Unknown> actions;

    /**
     * Gets the actions property
     * @return List<Unknown> value
     */
    public List<Unknown> getActions() {
        return this.actions;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("type", this.type);
        toReturn.put("id", this.id);
        toReturn.put("actions", this.actions);
        return toReturn;
    }

}