/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Input;


public class PauseAction {

    public PauseAction(long duration) {
        this.duration = long;
        this.type = "pause";
    }

    private final pause type;
    public getType(pause type) {
        this.type = type;
    }

    private final long duration;
    public getDuration(long duration) {
        this.duration = duration;
    }

}