/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Input;


public class PointerUpAction {

    public PointerUpAction(long button) {
        this.button = long;
        this.type = "pointerUp";
    }

    private final pointerUp type;
    public getType(pointerUp type) {
        this.type = type;
    }

    private final long button;
    public getButton(long button) {
        this.button = button;
    }

}