/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Log;


public class ConsoleLogEntry {

    public ConsoleLogEntry(String method) {
        this.method = String;
        this.type = "console";
        this.args = "Unknown[]";
    }

    private final console type;
    public getType(console type) {
        this.type = type;
    }

    private final String method;
    public getMethod(String method) {
        this.method = method;
    }

    private final Unknown[] args;
    public getArgs(Unknown[] args) {
        this.args = args;
    }

}