/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Log;


public class GenericLogEntry {

    public GenericLogEntry(String type) {
        this.type = String;
        
    }

    private final String type;
    public getType(String type) {
        this.type = type;
    }

}