/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.Log;


public class JavascriptLogEntry {

    public JavascriptLogEntry() {
        
        this.type = "javascript";
    }

    private final javascript type;
    public getType(javascript type) {
        this.type = type;
    }

}